language: csharp
dist: trusty
mono: none
dotnet: 2.1.2
branches:
 - only:
   - master
   - develop
 
before_script:
 - dotnet restore
 
script:
 - dotnet build NetCoreWebApplication1/NetCoreWebApplication1.csproj # .net core web application
 - dotnet build ConsoleApp3/ConsoleApp3.csproj # .net core console application