
FROM microsoft/dotnet:latest
COPY . /NetCoreWebApplication1
WORKDIR /NetCoreWebApplication1

RUN dotnet restore
RUN dotnet build NetCoreWebApplication1/NetCoreWebApplication1.csproj

EXPOSE 5000/tcp
ENV ASPNETCORE_URLS http://*:5000
ENV ASPNETCORE_ENVIRONMENT docker

ENTRYPOINT dotnet run